name: Run Fundamental Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"   # tiap hari jam 08:00 WIB

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests openai

      - name: Run bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py
